#!/bin/bash
# Xcode "Prepare engine" phase, step 2: write the engine this build expects,
# read from $RFM_ENGINE_DIR/VERSION, to $SCRIPT_OUTPUT_FILE_0 as Swift. The
# app's launch check compares the bundled engine with it.
#
# The file is rewritten only when its content changes, so a no-op build
# compiles nothing.

set -euo pipefail

version_file="${RFM_ENGINE_DIR:?}/VERSION"
out="${SCRIPT_OUTPUT_FILE_0:?}"

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

[[ -f "$version_file" ]] || die "no engine at ${RFM_ENGINE_DIR}; run scripts/build-engine.sh"

# The value of key $1. The last one wins, as in MoleEngine's EngineVersion.
# Values become Swift literals unescaped, so quotes and backslashes are refused.
value() {
    local found
    found="$(sed -n "s/^$1=//p" "$version_file" | tail -n 1)"
    [[ -n "$found" ]] || die "$version_file has no $1"
    case "$found" in
        *'"'* | *\\*) die "$1 in $version_file contains a quote or a backslash: $found" ;;
    esac
    printf '%s\n' "$found"
}

tag="$(value mole_tag)"
commit="$(value mole_commit)"
patches_sha="$(value patches_sha256)"
count="$(value patch_count)"
case "$count" in
    *[!0-9]*) die "patch_count in $version_file is not a number: $count" ;;
esac

mkdir -p "$(dirname "$out")"
tmp="$(mktemp "$out.XXXXXX")"
chmod 644 "$tmp"
cat > "$tmp" << SWIFT
// Generated by scripts/engine-expectation.sh from build/engine/VERSION. Do not edit.
enum EngineExpectation {
    static let moleTag = "$tag"
    static let moleCommit = "$commit"
    static let patchesSHA256 = "$patches_sha"
    static let patchCount = $count
}
SWIFT
if cmp -s "$tmp" "$out"; then
    rm -f "$tmp"
    echo "Engine expectation unchanged"
else
    mv -f "$tmp" "$out"
    echo "Engine expectation updated: $tag, $count patches"
fi
